# -*- coding: utf-8 -*-
"""Text-audio-prj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HzVo024A8ncWPQFwXay-p7P0jjSUzhIr
"""

!pip install -q openai-whisper transformers torch gtts
!apt-get -qq install ffmpeg

from google.colab import files

uploaded = files.upload()

import whisper

model = whisper.load_model("base")

result = model.transcribe("audio.mp3")  # replace with your filename

text = result["text"]

print("Recognized Text:")
print(text)

from transformers import pipeline

sentiment = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

result = sentiment(text)

label = result[0]["label"]
score = result[0]["score"]

print("Sentiment:", label)
print("Confidence:", round(score * 100, 2), "%")

output_text = f"The sentiment of the given audio is {label}"

print(output_text)

from gtts import gTTS

tts = gTTS(text=output_text, lang='en')

tts.save("result.mp3")

print("Output audio generated successfully!")

from IPython.display import Audio

Audio("result.mp3")